---
- name: Install collectd
  become: true
  become_user: root
  apt:
    name: "collectd={{ collectd_version }}"
    update_cache: true
  notify:
    - restart collectd
  when: ansible_distribution_version is version("22.04", "<")

# As of the time of this change collectd was not present for Ubuntu 22.04
# This step uses a proposed change to update collectd for Ubuntu 22.04 and
# may not support all functionality
# Conversation: https://bugs.launchpad.net/ubuntu/+source/collectd/+bug/1971093
- name: Download collectd-core package
  get_url:
    url: http://ftp.ubuntu.com/ubuntu/ubuntu/pool/universe/c/collectd/collectd-core_5.12.0-11_amd64.deb
    dest: /tmp/collectd-core_5.12.0-11_amd64.deb
  when: ansible_distribution_version == "22.04"

- name: Ensure collectd-core is installed
  apt:
    deb: /tmp/collectd-core_5.12.0-11_amd64.deb
    state: present
  become: true
  become_user: root
  when: ansible_distribution_version == "22.04"

- name: Download collectd package
  get_url:
    url: http://ftp.ubuntu.com/ubuntu/ubuntu/pool/universe/c/collectd/collectd_5.12.0-11_amd64.deb
    dest: /tmp/collectd_5.12.0-11_amd64.deb
  when: ansible_distribution_version == "22.04"

- name: Ensure collectd is installed
  apt:
    deb: /tmp/collectd_5.12.0-11_amd64.deb
    state: present
  become: true
  become_user: root
  notify:
    - restart collectd
  when: ansible_distribution_version == "22.04"

- include_tasks: server_mode.yml
  when: collectd_server_mode

- include_tasks: app_mode.yml
  when: not collectd_server_mode

- name: Create /etc/collectd/collectd.conf.d
  become: true
  become_user: root
  file:
    path=/etc/collectd/collectd.conf.d
    state=directory

- name: Copy collectd.conf
  become: true
  become_user: root
  template:
    src: "templates/etc/collectd/collectd.conf.d/{{ item }}.conf"
    dest: "/etc/collectd/collectd.conf.d/{{ item }}.conf"
    mode: 0644
    owner: root
    group: root
  with_items:
    "{{ collectd_scripts }}"
  notify:
    - restart collectd

- name: Enable the collectd service
  become: true
  become_user: root
  service:
    name: collectd
    enabled: true
