---
- name: Install collectd
  become: yes
  become_user: root
  apt:
    name: "collectd={{ collectd_version }}"
    update_cache: yes
  notify:
   - restart collectd

- include_tasks: server_mode.yml
  when: collectd_server_mode == true

- include_tasks: app_mode.yml
  when: collectd_server_mode == false

- name: Create /etc/collectd/collectd.conf.d
  become: yes
  become_user: root
  file:
      path=/etc/collectd/collectd.conf.d
      state=directory

- name: Copy collectd.conf
  become: yes
  become_user: root
  template:
    src: "templates/etc/collectd/collectd.conf.d/{{ item }}.conf"
    dest: "/etc/collectd/collectd.conf.d/{{ item }}.conf"
    mode: 0644
    owner: root
    group: root
  with_items:
    "{{ collectd_scripts }}"
  notify:
   - restart collectd

- name: Enable the collectd service
  become: yes
  become_user: root
  service:
    name: collectd
    enabled: yes
