---
- name: Install collectd
  become: true
  become_user: root
  apt:
    name: "collectd={{ collectd_version }}"
    update_cache: true
  notify:
    - restart collectd

- include_tasks: server_mode.yml
  when: collectd_server_mode

- include_tasks: app_mode.yml
  when: not collectd_server_mode

- name: Create /etc/collectd/collectd.conf.d
  become: true
  become_user: root
  file:
    path=/etc/collectd/collectd.conf.d
    state=directory

- name: Copy collectd.conf
  become: true
  become_user: root
  template:
    src: "templates/etc/collectd/collectd.conf.d/{{ item }}.conf"
    dest: "/etc/collectd/collectd.conf.d/{{ item }}.conf"
    mode: 0644
    owner: root
    group: root
  with_items:
    "{{ collectd_scripts }}"
  notify:
    - restart collectd

- name: Enable the collectd service
  become: true
  become_user: root
  service:
    name: collectd
    enabled: true
